#!/usr/bin/env python3
""""""
import redis
from typing import Union
import uuid


class Cache:
    """Creates Cache class"""
    def __init__(self,):
        """Initializes the cash instance"""
        self._redis = redis.Redis()
        self._redis.flushdb(True)

    def store(self, data: Union[str, bytes, int, float]) -> str:
        """
            enerate a random key (e.g. using uuid), store the input data
            in Redis using the random key and return the key.
        """
        key = str(uuid.uuid4())
        self._redis.set(key, data)
        return key
