-- creates a table users

DROP TABLE IF EXISTS users

CREATE TABLE IF NOT EXISTS users (
	id int AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	name VARCHAR(255),
	PRIMARY KEY (id),
	country ENUM('US', 'CO', 'TN') DEFAULT 'US' NOT NULL
);
